### ISSUE TITLE
original annotations of adj satellites uses wrong sense-key

### ISSUE THREAD

**Issue by arademaker** [own-pt/glosstag#18]
1. fix the sense keys in the XML files
2. adjust the XML to PLIST/JSON script to not fix it during transformation.

**Comment by hmuniz** [comment]
I started a lisp script to fix that in `ar-new+ukn` branch but I realize that a simple `sed` command solves the problem. In `princeton` branch run:
```bash
sed -i 's/%\(3\)\(:[0-9][0-9]:[0-9][0-9]:[[:print:]]\+:[0-9][0-9]\)/%5\2/' merged/* 
sed -i 's/%\(3\)\(:[0-9][0-9]:[0-9][0-9]:[[:print:]]\+:[0-9][0-9]\)/%5\2/' standoff/index.*
sed -i 's/%\(3\)\(:[0-9][0-9]:[0-9][0-9]:[[:print:]]\+:[0-9][0-9]\)/%5\2/' standoff/*/*/*
```
Do you see any problem with that solution? @arademaker

**Comment by hmuniz** [comment]
I will close this issue. The data in `merged` directory from `princeton` was updated via `sed` command commented before.
